"""
uploader.py  --  YouTube OAuth 2.0 uploader for Stickman Studio
===============================================================
Authenticates via OAuth 2.0 (desktop app flow) and uploads the
generated final.mp4 to YouTube as a private draft or public video.

Usage:
    from uploader import YouTubeUploader

    uploader = YouTubeUploader()
    url = uploader.authenticate_and_upload(
        video_path="projects/how_gravity_works/final.mp4",
        title="How Gravity Works",
        description="Animated educational short by Stickman Studio.",
        privacy_status="private",
    )
    print(f"Uploaded: {url}")
"""

from __future__ import annotations

import json
import logging
import os
import webbrowser
from pathlib import Path
from typing import Optional

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

log = logging.getLogger("stickman_studio.uploader")

_SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube",
]
"""youtube.upload + youtube = upload videos AND update their privacy status."""
_TOKEN_FILE = "youtube_token.json"
_CLIENT_SECRETS_FILENAME = "client_secrets.json"

_API_SERVICE_NAME = "youtube"
_API_VERSION = "v3"


def _find_client_secrets() -> Path:
    """Walk up from cwd to find client_secrets.json."""
    start = Path.cwd()
    for parent in [start] + list(start.parents):
        candidate = parent / _CLIENT_SECRETS_FILENAME
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(
        f"{_CLIENT_SECRETS_FILENAME} not found in any parent "
        f"directory of {start}. Place it in the project root."
    )


class YouTubeUploader:
    """Authenticate with YouTube and upload videos via OAuth 2.0.

    The OAuth token is cached to ``youtube_token.json`` so the user only
    needs to authorise once in the browser.  Refreshes are handled
    automatically.

    By default videos are uploaded as **private** then immediately
    transitioned to **public** (two‑step for reliability — the metadata
    is set during upload and only the status changes afterward).
    """

    def __init__(self, client_secrets_path: str | Path | None = None) -> None:
        self._client_secrets_path = Path(client_secrets_path) if client_secrets_path else _find_client_secrets()
        self._token_path = Path(_TOKEN_FILE)
        self._service = None

    # ------------------------------------------------------------------ #
    # Authentication
    # ------------------------------------------------------------------ #

    def authenticate(self) -> None:
        """Run OAuth 2.0 flow, caching the token locally.

        Opens a browser for the user to grant access.  On subsequent runs
        the cached token is loaded and refreshed if needed.
        """
        creds = None

        if self._token_path.is_file():
            try:
                creds = Credentials.from_authorized_user_file(
                    str(self._token_path), _SCOPES
                )
            except Exception as exc:
                log.warning("Failed to load cached token: %s", exc)

        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            self._save_token(creds)
            log.info("OAuth token refreshed.")
        elif not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file(
                str(self._client_secrets_path), _SCOPES
            )
            creds = flow.run_local_server(port=0, open_browser=True)
            self._save_token(creds)
            log.info("OAuth flow complete. Token saved.")

        from googleapiclient.discovery import build

        self._service = build(_API_SERVICE_NAME, _API_VERSION, credentials=creds)

    def _save_token(self, creds: Credentials) -> None:
        self._token_path.write_text(creds.to_json(), encoding="utf-8")

    # ------------------------------------------------------------------ #
    # Upload
    # ------------------------------------------------------------------ #

    def upload(
        self,
        video_path: str | Path,
        title: str = "Stickman Studio Video",
        description: str = "Generated by Stickman Studio",
        tags: Optional[list[str]] = None,
        category_id: str = "22",
        privacy_status: str = "private",
    ) -> str:
        """Upload a video file to YouTube.

        Args:
            video_path: Path to the MP4 file.
            title: YouTube video title.
            description: YouTube video description.
            tags: Optional list of tag strings.
            category_id: YouTube category ID (22 = People & Blogs).
            privacy_status: ``"private"`` (draft), ``"unlisted"``, or
                ``"public"``.

        Returns:
            The URL of the uploaded video.

        Raises:
            RuntimeError: If authentication has not been completed.
            FileNotFoundError: If ``video_path`` does not exist.
        """
        if self._service is None:
            raise RuntimeError(
                "Not authenticated. Call authenticate() first."
            )

        path = Path(video_path)
        if not path.is_file():
            raise FileNotFoundError(f"Video file not found: {path}")

        body = {
            "snippet": {
                "title": title,
                "description": description,
                "tags": tags or [],
                "categoryId": category_id,
            },
            "status": {
                "privacyStatus": privacy_status,
                "selfDeclaredMadeForKids": False,
            },
        }

        from googleapiclient.http import MediaFileUpload

        media = MediaFileUpload(str(path), chunksize=-1, resumable=True)

        log.info(
            "Uploading '%s' (%d bytes) as '%s' ...",
            path.name, path.stat().st_size, privacy_status,
        )

        request = self._service.videos().insert(
            part="snippet,status",
            body=body,
            media_body=media,
        )

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                pct = int(status.progress() * 100)
                log.info("  Upload progress: %d%%", pct)

        video_id = response.get("id")
        url = f"https://youtu.be/{video_id}"
        log.info("Upload complete: %s", url)
        return url

    # ------------------------------------------------------------------ #
    # Convenience
    # ------------------------------------------------------------------ #

    def authenticate_and_upload(
        self,
        video_path: str | Path,
        title: str = "Stickman Studio Video",
        description: str = "Generated by Stickman Studio",
        tags: Optional[list[str]] = None,
        privacy_status: str = "private",
        auto_publish: bool = True,
    ) -> str:
        """Authenticate (if needed) then upload.

        When ``auto_publish`` is ``True`` (default) the video is first
        uploaded as **private** and, on success, immediately transitioned
        to **public**.  Metadata (title, description, tags) is set during
        the upload and preserved through the status change.

        When ``auto_publish`` is ``False`` the video is left at the given
        ``privacy_status`` (typically ``"private"``).
        """
        self.authenticate()
        url = self.upload(
            video_path=video_path,
            title=title,
            description=description,
            tags=tags,
            privacy_status="private",  # always upload private first
        )

        if auto_publish:
            video_id = self.get_video_id_from_url(url)
            url = self.make_public(video_id)
            log.info("Published: %s  (%s)", title, url)

        return url

    def make_public(self, video_id: str) -> str:
        """Update an existing YouTube video's privacy status to 'public'.

        The video must have been uploaded by this authenticated account.

        Args:
            video_id: The YouTube video ID (e.g. ``"dQw4w9WgXcQ"``).

        Returns:
            The video URL.
        """
        if self._service is None:
            raise RuntimeError("Not authenticated. Call authenticate() first.")

        self._service.videos().update(
            part="status",
            body={
                "id": video_id,
                "status": {"privacyStatus": "public"},
            },
        ).execute()

        url = f"https://youtu.be/{video_id}"
        log.info("Made public: %s", url)
        return url

    def get_video_id_from_url(self, url: str) -> str:
        """Extract the YouTube video ID from a youtu.be or youtube.com URL."""
        import re
        m = re.search(r"(?:youtu\.be/|v=|/v/|youtube\.com/watch\?v=)([a-zA-Z0-9_-]{11})", url)
        if not m:
            raise ValueError(f"Could not extract video ID from URL: {url}")
        return m.group(1)


def upload_video(
    file_path: str | Path,
    title: str = "Stickman Studio Video",
    description: str = "Generated by Stickman Studio",
    tags: list[str] | None = None,
    auto_publish: bool = True,
) -> str:
    """One-shot convenience: authenticate, upload, and auto‑publish."""
    return YouTubeUploader().authenticate_and_upload(
        video_path=file_path,
        title=title,
        description=description,
        tags=tags,
        auto_publish=auto_publish,
    )


def make_public(video_url_or_id: str) -> str:
    """One-shot convenience: make a video public from its URL or ID."""
    uploader = YouTubeUploader()
    uploader.authenticate()
    # If it looks like a URL, extract the ID
    if video_url_or_id.startswith("http"):
        video_id = uploader.get_video_id_from_url(video_url_or_id)
    else:
        video_id = video_url_or_id
    return uploader.make_public(video_id)
